### ISSUE TITLE
What's wrong with Amazon?

### ISSUE THREAD

**Issue by skytux** [checkmyhttps/checkmyhttps#16]
This add-on is really useful, thanks a lot.

Here I can found there are large whitelist for some domains including Amazon.
https://github.com/checkmyhttps/checkmyhttps/blob/master/server-php/www/api_whitelist.php

What's wrong with it?
Is it still in use on the production server?

**Comment by checkmyhttps** [comment]
Some (big) Web services are duplicated on several Internet servers which haven't the same @IP. To perform that, they often use a CDN services like "Akamai", "Limelight", "Level 3", "CloudFlare", etc. When you connect on these Web services, the CDN connect your browser to one of these servers. When Checkmyhttps server contacts again the same service, it can be redirected to an other server (often with an other certificate). It is then a "false positive". It's why we've creates a "whitelist".

**Comment by skytux** [comment]
Okay, I understand the quick fix to avoid false-positive alarm.

But I think it's a bad idea to whitelist those services and return a green tick to the add-on, this could create a false sentiment of security if user's browsing to specific websites using CDN are targeted.

Maybe it could be a great improvement to handle this another way.

A quickfix could be displaying a specific icon in the browser, optionnaly with description when hovering it if not explicit enough.
This info could be returned in an additional payload within the same request for compatibility issues between old add-ons and new server (it could be great to add a request version in the payload itself, like an integrated header).

Another idea, with (A LOT) more programming and testing, may be collecting the IP resolved by the browser (it's shown inside networks requests in dev tools) with the WebEx API and HAR log of request :

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.network
http://www.softwareishard.com/blog/har-12-spec/#entries

With this, it should be possible to force a request from the checkmyhttps server to this IP address.
Also, it could be a good idea to check if DNS was not poisoned, with a server-side hostname resolution and compare if the add-on reported IP address is found inside the server-side DNS answer.

**Comment by QuentinClrt** [comment]
Malek, thanks a lot for your interesting reply. As a matter of fact, the **second solution** you have written might be a feasible way to harden the current security but our architecture will totally be modifed. We will, then, cogitate about your solution and try to take it to the next level.

**Comment by rexy74** [comment]
Indeed, this is a good idea to work about the second solution. If we do so, we accept CMH won't work on Android.

**Comment by cneukom** [comment]
I see another problem that probably will arise when implementing the second approach. It is a **must** to check whether the IP address obtained from the client is listed in the "official" DNS response. However, due to [GeoDNS](https://en.wikipedia.org/wiki/GeoDNS), the check server might get a different set of IP addresses from the DNS resolution. Hence, it's possible, that the IP address the client has connected to is not spoofed but still is not resolved by the check server. In these cases, the verification will still not be possible.

**Comment by Shiluba** [comment]
You are right @cneukom, we already planned to add a "valid IP check" but GeoDNS is indeed a problem we will still have to face.
Concerning your second point, if a client checks a website whose FQDN is not resolved by our check server, it would not be an issue, as our CheckMyHTTPS clients now send the IP resolved by the client's machine. In this case, our check server will just try to connect to this IP with the given FQDN, without having to resolve it with a DNS server.

Thanks for your interest in the project.

Sylvain
